spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ntest?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 120708
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.wzw.entity